GET http://localhost:5251

HTTP/1.1 200  - OK
connection: close
content-type: text/plain; charset=utf-8
date: Sat, 06 Sep 2025 04:34:42 GMT
server: Kestrel
transfer-encoding: chunked
###
GET http://localhost:5251/games

HTTP/1.1 200  - OK
connection: close
content-type: application/json; charset=utf-8
date: Sat, 06 Sep 2025 04:34:52 GMT
server: Kestrel
transfer-encoding: chunked
###
GET http://localhost:5251/games/3

HTTP/1.1 200  - OK
connection: close
content-type: application/json; charset=utf-8
date: Sat, 06 Sep 2025 04:34:47 GMT
server: Kestrel
transfer-encoding: chunked
###
GET http://localhost:5251/games/4

HTTP/1.1 200  - OK
connection: close
content-type: application/json; charset=utf-8
date: Sat, 06 Sep 2025 04:34:42 GMT
server: Kestrel
transfer-encoding: chunked
###
POST http://localhost:5251/games
Content-Type:application/json
{
    "name":"Minecraft",
    "genre":"Kids and Family",
    "price": 19.99,
    "releaseDate":"2023-11-04"
}

HTTP/1.1 201  - Created
connection: close
content-type: application/json; charset=utf-8
date: Sat, 06 Sep 2025 04:34:42 GMT
server: Kestrel
location: http://localhost:5251/games/4
transfer-encoding: chunked