GET http://localhost:5251

HTTP/1.1 200  - OK
connection: close
content-type: text/plain; charset=utf-8
date: Sun, 07 Sep 2025 16:53:23 GMT
server: Kestrel
transfer-encoding: chunked
###
GET http://localhost:5251/games

HTTP/1.1 200  - OK
connection: close
content-type: application/json; charset=utf-8
date: Sun, 07 Sep 2025 16:53:43 GMT
server: Kestrel
transfer-encoding: chunked
###
GET http://localhost:5251/games/3

HTTP/1.1 200  - OK
connection: close
content-type: application/json; charset=utf-8
date: Sun, 07 Sep 2025 16:53:23 GMT
server: Kestrel
transfer-encoding: chunked
###
GET http://localhost:5251/games/4

HTTP/1.1 200  - OK
connection: close
content-type: application/json; charset=utf-8
date: Sun, 07 Sep 2025 16:53:38 GMT
server: Kestrel
transfer-encoding: chunked
###
POST http://localhost:5251/games
Content-Type:application/json
{
    "name":"Minecraft",
    "genre":"Kids and Family",
    "price": 19.99,
    "releaseDate":"2023-11-04"
}

HTTP/1.1 201  - Created
connection: close
content-type: application/json; charset=utf-8
date: Sun, 07 Sep 2025 16:53:33 GMT
server: Kestrel
location: http://localhost:5251/games/5
transfer-encoding: chunked
###
POST http://localhost:5251/api/tasks
Content-Type:application/json
{
  "title": "Learn ASP.NET",
  "description": "Understand Web API basics",
  "isCompleted": false
}

HTTP/1.1 404  - Not Found
content-length: 0
connection: close
date: Sun, 14 Sep 2025 07:23:26 GMT
server: Kestrel